# Generated by Django 2.1.7 on 2019-03-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190319_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='addr',
            new_name='address',
        ),
    ]
