# Generated by Django 2.1.7 on 2019-03-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
