# Generated by Django 2.1.7 on 2019-03-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20190319_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='全国名校', max_length=10, verbose_name='机构标签'),
        ),
    ]
