# Generated by Django 2.1.7 on 2019-03-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_is_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student',
            new_name='students',
        ),
    ]
